### PR TITLE
Renaming SmartSignalsShared

### PR DESCRIPTION
**Pull request by efvink**
Note - review only after PR #88  is approved

Renaming: namespace, project name, SmartSignal*, SmartSignalResultItem*, Signal

### CODE REVIEW

**Comment by EranGon** [comment]
>     public class SmartSignalLoaderTests

SmartDetectorLoaderTests

---
Refers to: test/SmartSignalsSharedTests/SmartSignalLoaderTests.cs:28 in abf852a. [](commit_id = abf852a251bd3ea4794f9d3c6fb3b1d73bbf08f2, deletion_comment = False)

**Comment by EranGon** [comment]
> <Project Sdk="Microsoft.NET.Sdk">

please rename this project as well to match

---
Refers to: test/SmartSignalsSharedTests/SmartSignalsSharedTests.csproj:1 in abf852a. [](commit_id = abf852a251bd3ea4794f9d3c6fb3b1d73bbf08f2, deletion_comment = False)

**Comment by efvink** [comment]
> <Project Sdk="Microsoft.NET.Sdk">

I will change it later

---
In reply to: [370715429](https://github.com/liadtal/Smart-Alerts/pull/89#issuecomment-370715429) [](ancestors = 370715429)

---
Refers to: test/SmartSignalsSharedTests/SmartSignalsSharedTests.csproj:1 in abf852a. [](commit_id = abf852a251bd3ea4794f9d3c6fb3b1d73bbf08f2, deletion_comment = False)

**Comment by efvink** [comment]
>     public class SmartSignalLoaderTests

I will change it later

---
In reply to: [370715335](https://github.com/liadtal/Smart-Alerts/pull/89#issuecomment-370715335) [](ancestors = 370715335)

---
Refers to: test/SmartSignalsSharedTests/SmartSignalLoaderTests.cs:28 in abf852a. [](commit_id = abf852a251bd3ea4794f9d3c6fb3b1d73bbf08f2, deletion_comment = False)

**Pull request merged**
